[2024-02-03 20:15:09,681: INFO: main: Welcom to our custom log]
[2024-02-04 17:32:24,221: INFO: main: Welcom to our custom log]
[2024-02-04 17:32:24,221: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-04 17:32:24,222: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-04 17:32:24,222: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 17:32:24,222: INFO: common: created directory at: artifacts]
[2024-02-04 17:32:24,222: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-04 17:32:24,222: ERROR: main: name 'os' is not defined]
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    data_ingestion.main()
  File "/home/fintechsys/MLflow projects/kidney-Disease-classification-Deep-Learning--project/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "/home/fintechsys/MLflow projects/kidney-Disease-classification-Deep-Learning--project/src/cnnClassifier/components/data_ingestion.py", line 30, in download_file
    raise e
  File "/home/fintechsys/MLflow projects/kidney-Disease-classification-Deep-Learning--project/src/cnnClassifier/components/data_ingestion.py", line 20, in download_file
    os.makedirs("artifacts/data_ingestion", exist_ok=True)
NameError: name 'os' is not defined
[2024-02-04 17:33:31,259: INFO: main: Welcom to our custom log]
[2024-02-04 17:33:31,259: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-04 17:33:31,260: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-04 17:33:31,260: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 17:33:31,260: INFO: common: created directory at: artifacts]
[2024-02-04 17:33:31,260: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-04 17:33:31,260: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/17iriTzXvzVbMtVrI1mNW0uZAwgqM9tE3/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 17:35:29,895: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/17iriTzXvzVbMtVrI1mNW0uZAwgqM9tE3/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 17:35:30,502: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-04 18:17:56,465: INFO: main: Welcom to our custom log]
[2024-02-04 18:17:56,465: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-04 18:17:56,466: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-04 18:17:56,466: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 18:17:56,466: INFO: common: created directory at: artifacts]
[2024-02-04 18:17:56,467: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-04 18:17:56,467: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/17iriTzXvzVbMtVrI1mNW0uZAwgqM9tE3/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 18:19:55,792: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/17iriTzXvzVbMtVrI1mNW0uZAwgqM9tE3/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 18:19:56,455: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-04 19:47:01,387: INFO: main: Welcom to our custom log]
[2024-02-04 19:47:01,388: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-04 19:47:01,389: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-04 19:47:01,389: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-04 19:47:01,389: INFO: common: created directory at: artifacts]
[2024-02-04 19:47:01,390: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-04 19:47:01,390: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/17iriTzXvzVbMtVrI1mNW0uZAwgqM9tE3/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 19:48:59,368: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/17iriTzXvzVbMtVrI1mNW0uZAwgqM9tE3/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-04 19:49:00,048: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-05 10:07:55,751: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 10:07:55,755: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 10:07:55,758: INFO: common: created directory at: artifacts]
[2024-02-05 10:09:08,970: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 10:09:08,972: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 10:09:08,973: INFO: common: created directory at: artifacts]
[2024-02-05 10:09:12,476: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 10:09:12,478: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 10:09:12,479: INFO: common: created directory at: artifacts]
[2024-02-05 10:10:39,113: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 10:10:39,115: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 10:10:39,116: INFO: common: created directory at: artifacts]
[2024-02-05 10:10:39,117: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-05 10:11:29,967: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-05 16:09:05,580: INFO: main: Welcom to our custom log]
[2024-02-05 16:09:05,581: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-05 16:09:05,582: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 16:09:05,583: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 16:09:05,583: INFO: common: created directory at: artifacts]
[2024-02-05 16:09:05,583: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-05 16:09:05,583: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/17iriTzXvzVbMtVrI1mNW0uZAwgqM9tE3/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-05 16:11:01,481: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/17iriTzXvzVbMtVrI1mNW0uZAwgqM9tE3/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-05 16:11:02,139: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-05 16:11:02,139: INFO: main: *******************]
[2024-02-05 16:11:02,140: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-05 16:11:02,140: ERROR: main: name 'PrepareBaseModelTrainingPipeline' is not defined]
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    prepare_base_model = PrepareBaseModelTrainingPipeline()
NameError: name 'PrepareBaseModelTrainingPipeline' is not defined
[2024-02-05 16:12:31,095: INFO: main: Welcom to our custom log]
[2024-02-05 16:12:31,095: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-05 16:12:31,097: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 16:12:31,098: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 16:12:31,098: INFO: common: created directory at: artifacts]
[2024-02-05 16:12:31,098: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-05 16:12:31,098: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/17iriTzXvzVbMtVrI1mNW0uZAwgqM9tE3/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-05 16:14:31,054: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/17iriTzXvzVbMtVrI1mNW0uZAwgqM9tE3/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-05 16:14:31,736: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-05 16:14:31,736: INFO: main: *******************]
[2024-02-05 16:14:31,736: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-05 16:14:31,737: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 16:14:31,738: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 16:14:31,738: INFO: common: created directory at: artifacts]
[2024-02-05 16:14:31,738: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-05 16:14:32,083: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-05 16:14:32,348: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-05 17:00:50,749: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 17:00:50,751: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 17:00:50,752: INFO: common: created directory at: artifacts]
[2024-02-05 17:00:50,753: INFO: common: created directory at: artifacts/training]
[2024-02-05 17:03:07,817: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 17:03:07,819: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 17:03:07,820: INFO: common: created directory at: artifacts]
[2024-02-05 17:03:07,821: INFO: common: created directory at: artifacts/training]
[2024-02-05 17:05:04,104: INFO: main: Welcom to our custom log]
[2024-02-05 17:05:04,104: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-05 17:05:04,105: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 17:05:04,106: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 17:05:04,106: INFO: common: created directory at: artifacts]
[2024-02-05 17:05:04,106: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-05 17:05:04,106: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/17iriTzXvzVbMtVrI1mNW0uZAwgqM9tE3/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-05 17:07:00,952: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/17iriTzXvzVbMtVrI1mNW0uZAwgqM9tE3/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-02-05 17:07:01,571: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-05 17:07:01,571: INFO: main: *******************]
[2024-02-05 17:07:01,572: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-05 17:07:01,573: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 17:07:01,574: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 17:07:01,574: INFO: common: created directory at: artifacts]
[2024-02-05 17:07:01,574: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-05 17:07:01,850: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-05 17:07:02,000: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-05 17:08:42,141: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 17:08:42,143: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 17:08:42,143: INFO: common: created directory at: artifacts]
[2024-02-05 17:08:42,144: INFO: common: created directory at: artifacts/training]
[2024-02-05 17:17:35,329: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 17:17:35,332: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 17:17:35,333: INFO: common: created directory at: artifacts]
[2024-02-05 17:17:35,334: INFO: common: created directory at: artifacts/training]
[2024-02-05 17:23:08,379: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 17:23:08,382: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 17:23:08,383: INFO: common: created directory at: artifacts]
[2024-02-05 17:23:08,384: INFO: common: created directory at: artifacts/training]
[2024-02-05 17:27:42,564: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 17:27:42,567: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 17:27:42,569: INFO: common: created directory at: artifacts]
[2024-02-05 17:27:42,569: INFO: common: created directory at: artifacts/training]
[2024-02-05 17:31:28,294: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 17:31:28,296: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 17:31:28,296: INFO: common: created directory at: artifacts]
[2024-02-05 17:31:28,297: INFO: common: created directory at: artifacts/training]
[2024-02-05 17:32:13,965: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 17:32:13,969: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 17:32:13,970: INFO: common: created directory at: artifacts]
[2024-02-05 17:32:13,970: INFO: common: created directory at: artifacts/training]
[2024-02-05 17:36:17,520: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 17:36:17,522: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 17:36:17,523: INFO: common: created directory at: artifacts]
[2024-02-05 17:36:17,524: INFO: common: created directory at: artifacts/training]
[2024-02-05 17:54:45,557: INFO: main: Welcom to our custom log]
[2024-02-05 17:54:45,557: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-05 17:54:45,558: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 17:54:45,559: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 17:54:45,560: INFO: common: created directory at: artifacts]
[2024-02-05 17:54:45,560: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-05 17:54:45,560: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-05 17:55:37,693: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-05 17:55:38,104: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-05 17:55:38,104: INFO: main: *******************]
[2024-02-05 17:55:38,104: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-05 17:55:38,105: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 17:55:38,107: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 17:55:38,107: INFO: common: created directory at: artifacts]
[2024-02-05 17:55:38,107: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-05 17:55:38,574: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-05 17:55:38,770: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-05 17:55:38,770: INFO: main: *******************]
[2024-02-05 17:55:38,770: INFO: main: >>>>>> stage training started <<<<<<]
[2024-02-05 17:55:38,771: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 17:55:38,772: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 17:55:38,772: INFO: common: created directory at: artifacts]
[2024-02-05 17:55:38,773: INFO: common: created directory at: artifacts/training]
[2024-02-05 17:55:39,037: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/kidney-CT-scan-image']
Traceback (most recent call last):
  File "main.py", line 38, in <module>
    prepare_base_model.main()
  File "/home/fintechsys/MLflow projects/kidney-Disease-classification-Deep-Learning--project/src/cnnClassifier/pipeline/stage_03_model_training.py", line 20, in main
    training.train_valid_generator()
  File "/home/fintechsys/MLflow projects/kidney-Disease-classification-Deep-Learning--project/src/cnnClassifier/components/model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/preprocessing/image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/preprocessing/image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/kidney-CT-scan-image'
[2024-02-05 18:00:33,550: INFO: main: Welcom to our custom log]
[2024-02-05 18:00:33,550: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-05 18:00:33,551: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 18:00:33,552: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 18:00:33,553: INFO: common: created directory at: artifacts]
[2024-02-05 18:00:33,553: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-05 18:00:33,553: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-05 18:01:25,977: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-05 18:01:26,415: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-05 18:01:26,415: INFO: main: *******************]
[2024-02-05 18:01:26,415: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-05 18:01:26,417: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 18:01:26,419: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 18:01:26,420: INFO: common: created directory at: artifacts]
[2024-02-05 18:01:26,420: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-05 18:01:26,914: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-05 18:01:27,202: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-05 18:01:27,203: INFO: main: *******************]
[2024-02-05 18:01:27,203: INFO: main: >>>>>> stage training started <<<<<<]
[2024-02-05 18:01:27,206: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 18:01:27,207: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 18:01:27,207: INFO: common: created directory at: artifacts]
[2024-02-05 18:01:27,208: INFO: common: created directory at: artifacts/training]
[2024-02-05 18:01:27,541: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/kidney-CT-scan-image']
Traceback (most recent call last):
  File "main.py", line 38, in <module>
    prepare_base_model.main()
  File "/home/fintechsys/MLflow projects/kidney-Disease-classification-Deep-Learning--project/src/cnnClassifier/pipeline/stage_03_model_training.py", line 20, in main
    training.train_valid_generator()
  File "/home/fintechsys/MLflow projects/kidney-Disease-classification-Deep-Learning--project/src/cnnClassifier/components/model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/preprocessing/image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/preprocessing/image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/kidney-CT-scan-image'
[2024-02-05 18:04:21,008: INFO: main: Welcom to our custom log]
[2024-02-05 18:04:21,008: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-05 18:04:21,010: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 18:04:21,011: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 18:04:21,011: INFO: common: created directory at: artifacts]
[2024-02-05 18:04:21,011: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-05 18:04:21,011: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-05 18:05:11,384: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-05 18:05:11,657: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-05 18:05:11,657: INFO: main: *******************]
[2024-02-05 18:05:11,657: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-05 18:05:11,659: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 18:05:11,659: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 18:05:11,660: INFO: common: created directory at: artifacts]
[2024-02-05 18:05:11,660: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-05 18:05:11,950: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-05 18:05:12,130: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-05 18:05:12,130: INFO: main: *******************]
[2024-02-05 18:05:12,130: INFO: main: >>>>>> stage training started <<<<<<]
[2024-02-05 18:05:12,131: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 18:05:12,132: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 18:05:12,132: INFO: common: created directory at: artifacts]
[2024-02-05 18:05:12,132: INFO: common: created directory at: artifacts/training]
[2024-02-05 18:05:52,891: INFO: main: >>>>>> stage training completed <<<<<<

x==========x]
[2024-02-05 23:29:10,782: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-05 23:29:10,787: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-05 23:29:10,788: INFO: common: created directory at: artifacts]
[2024-02-05 23:29:22,357: INFO: common: json file saved at: scores.json]
[2024-02-05 23:29:25,821: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-05 23:29:26,233: INFO: builder_impl: Assets written to: /tmp/tmpas0tsrlf/model/data/model/assets]
[2024-02-06 20:15:41,543: INFO: main: Welcom to our custom log]
[2024-02-06 20:15:41,543: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-06 20:15:41,545: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 20:15:41,546: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 20:15:41,546: INFO: common: created directory at: artifacts]
[2024-02-06 20:15:41,546: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-06 20:15:41,546: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-06 20:16:33,142: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-06 20:16:33,427: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-06 20:16:33,427: INFO: main: *******************]
[2024-02-06 20:16:33,427: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-06 20:16:33,429: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 20:16:33,429: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 20:16:33,430: INFO: common: created directory at: artifacts]
[2024-02-06 20:16:33,430: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-06 20:16:33,700: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-06 20:16:33,906: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-06 20:16:33,906: INFO: main: *******************]
[2024-02-06 20:16:33,906: INFO: main: >>>>>> stage training started <<<<<<]
[2024-02-06 20:16:33,907: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 20:16:33,908: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 20:16:33,908: INFO: common: created directory at: artifacts]
[2024-02-06 20:16:33,908: INFO: common: created directory at: artifacts/training]
[2024-02-06 20:17:29,436: INFO: main: >>>>>> stage training completed <<<<<<

x==========x]
[2024-02-06 20:17:29,436: INFO: main: *******************]
[2024-02-06 20:17:29,436: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-02-06 20:17:29,438: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 20:17:29,438: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 20:17:29,439: INFO: common: created directory at: artifacts]
[2024-02-06 20:17:47,312: INFO: common: json file saved at: scores.json]
[2024-02-06 20:17:47,314: INFO: common: json file saved at: scores.json]
[2024-02-06 20:17:47,314: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-02-06 20:19:33,695: INFO: main: Welcom to our custom log]
[2024-02-06 20:19:33,695: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-06 20:19:33,697: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 20:19:33,698: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 20:19:33,698: INFO: common: created directory at: artifacts]
[2024-02-06 20:19:33,698: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-06 20:19:33,698: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-06 20:20:25,786: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-06 20:20:26,077: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-06 20:20:26,077: INFO: main: *******************]
[2024-02-06 20:20:26,077: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-06 20:20:26,078: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 20:20:26,079: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 20:20:26,079: INFO: common: created directory at: artifacts]
[2024-02-06 20:20:26,079: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-06 20:20:26,346: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-06 20:20:26,536: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-06 20:20:26,536: INFO: main: *******************]
[2024-02-06 20:20:26,536: INFO: main: >>>>>> stage training started <<<<<<]
[2024-02-06 20:20:26,538: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 20:20:26,539: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 20:20:26,539: INFO: common: created directory at: artifacts]
[2024-02-06 20:20:26,539: INFO: common: created directory at: artifacts/training]
[2024-02-06 20:21:22,412: INFO: main: >>>>>> stage training completed <<<<<<

x==========x]
[2024-02-06 20:21:22,412: INFO: main: *******************]
[2024-02-06 20:21:22,412: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-02-06 20:21:22,414: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 20:21:22,415: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 20:21:22,415: INFO: common: created directory at: artifacts]
[2024-02-06 20:21:40,155: INFO: common: json file saved at: scores.json]
[2024-02-06 20:21:40,155: INFO: common: json file saved at: scores.json]
[2024-02-06 20:21:43,512: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-06 20:21:43,871: INFO: builder_impl: Assets written to: /tmp/tmptu6wuv85/model/data/model/assets]
[2024-02-06 20:24:34,002: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-02-06 20:25:05,757: INFO: main: Welcom to our custom log]
[2024-02-06 20:25:05,757: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-06 20:25:05,759: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 20:25:05,760: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 20:25:05,760: INFO: common: created directory at: artifacts]
[2024-02-06 20:25:05,760: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-06 20:25:05,760: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-06 20:25:57,266: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-06 20:25:57,566: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-06 20:25:57,566: INFO: main: *******************]
[2024-02-06 20:25:57,566: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-06 20:25:57,567: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 20:25:57,568: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 20:25:57,568: INFO: common: created directory at: artifacts]
[2024-02-06 20:25:57,568: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-06 20:25:57,830: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-06 20:25:58,012: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-06 20:25:58,012: INFO: main: *******************]
[2024-02-06 20:25:58,012: INFO: main: >>>>>> stage training started <<<<<<]
[2024-02-06 20:25:58,013: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 20:25:58,014: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 20:25:58,015: INFO: common: created directory at: artifacts]
[2024-02-06 20:25:58,015: INFO: common: created directory at: artifacts/training]
[2024-02-06 20:26:00,948: ERROR: main: Graph execution error:

Detected at node 'categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):
    File "main.py", line 41, in <module>
      prepare_base_model.main()
    File "/home/fintechsys/MLflow projects/kidney-Disease-classification-Deep-Learning--project/src/cnnClassifier/pipeline/stage_03_model_training.py", line 21, in main
      training.train()
    File "/home/fintechsys/MLflow projects/kidney-Disease-classification-Deep-Learning--project/src/cnnClassifier/components/model_training.py", line 76, in train
      self.model.fit(
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/training.py", line 1051, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/training.py", line 1109, in compute_loss
      return self.compiled_loss(
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/losses.py", line 142, in __call__
      losses = call_fn(y_true, y_pred)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/losses.py", line 268, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/losses.py", line 1984, in categorical_crossentropy
      return backend.categorical_crossentropy(
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/backend.py", line 5565, in categorical_crossentropy
      return tf.nn.softmax_cross_entropy_with_logits(
Node: 'categorical_crossentropy/softmax_cross_entropy_with_logits'
logits and labels must be broadcastable: logits_size=[16,3] labels_size=[16,2]
	 [[{{node categorical_crossentropy/softmax_cross_entropy_with_logits}}]] [Op:__inference_train_function_1463]]
Traceback (most recent call last):
  File "main.py", line 41, in <module>
    prepare_base_model.main()
  File "/home/fintechsys/MLflow projects/kidney-Disease-classification-Deep-Learning--project/src/cnnClassifier/pipeline/stage_03_model_training.py", line 21, in main
    training.train()
  File "/home/fintechsys/MLflow projects/kidney-Disease-classification-Deep-Learning--project/src/cnnClassifier/components/model_training.py", line 76, in train
    self.model.fit(
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):
    File "main.py", line 41, in <module>
      prepare_base_model.main()
    File "/home/fintechsys/MLflow projects/kidney-Disease-classification-Deep-Learning--project/src/cnnClassifier/pipeline/stage_03_model_training.py", line 21, in main
      training.train()
    File "/home/fintechsys/MLflow projects/kidney-Disease-classification-Deep-Learning--project/src/cnnClassifier/components/model_training.py", line 76, in train
      self.model.fit(
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/training.py", line 1051, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/training.py", line 1109, in compute_loss
      return self.compiled_loss(
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/losses.py", line 142, in __call__
      losses = call_fn(y_true, y_pred)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/losses.py", line 268, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/losses.py", line 1984, in categorical_crossentropy
      return backend.categorical_crossentropy(
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/backend.py", line 5565, in categorical_crossentropy
      return tf.nn.softmax_cross_entropy_with_logits(
Node: 'categorical_crossentropy/softmax_cross_entropy_with_logits'
logits and labels must be broadcastable: logits_size=[16,3] labels_size=[16,2]
	 [[{{node categorical_crossentropy/softmax_cross_entropy_with_logits}}]] [Op:__inference_train_function_1463]
[2024-02-06 20:26:42,081: INFO: main: Welcom to our custom log]
[2024-02-06 20:26:42,081: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-06 20:26:42,083: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 20:26:42,084: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 20:26:42,084: INFO: common: created directory at: artifacts]
[2024-02-06 20:26:42,084: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-06 20:26:42,084: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-06 20:27:33,188: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-06 20:27:33,480: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-06 20:27:33,480: INFO: main: *******************]
[2024-02-06 20:27:33,480: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-06 20:27:33,481: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 20:27:33,482: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 20:27:33,482: INFO: common: created directory at: artifacts]
[2024-02-06 20:27:33,482: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-06 20:27:33,746: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-06 20:27:33,933: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-06 20:27:33,933: INFO: main: *******************]
[2024-02-06 20:27:33,933: INFO: main: >>>>>> stage training started <<<<<<]
[2024-02-06 20:27:33,935: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 20:27:33,936: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 20:27:33,936: INFO: common: created directory at: artifacts]
[2024-02-06 20:27:33,936: INFO: common: created directory at: artifacts/training]
[2024-02-06 20:27:36,867: ERROR: main: Graph execution error:

Detected at node 'categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):
    File "main.py", line 41, in <module>
      prepare_base_model.main()
    File "/home/fintechsys/MLflow projects/kidney-Disease-classification-Deep-Learning--project/src/cnnClassifier/pipeline/stage_03_model_training.py", line 21, in main
      training.train()
    File "/home/fintechsys/MLflow projects/kidney-Disease-classification-Deep-Learning--project/src/cnnClassifier/components/model_training.py", line 76, in train
      self.model.fit(
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/training.py", line 1051, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/training.py", line 1109, in compute_loss
      return self.compiled_loss(
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/losses.py", line 142, in __call__
      losses = call_fn(y_true, y_pred)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/losses.py", line 268, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/losses.py", line 1984, in categorical_crossentropy
      return backend.categorical_crossentropy(
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/backend.py", line 5565, in categorical_crossentropy
      return tf.nn.softmax_cross_entropy_with_logits(
Node: 'categorical_crossentropy/softmax_cross_entropy_with_logits'
logits and labels must be broadcastable: logits_size=[16,3] labels_size=[16,2]
	 [[{{node categorical_crossentropy/softmax_cross_entropy_with_logits}}]] [Op:__inference_train_function_1463]]
Traceback (most recent call last):
  File "main.py", line 41, in <module>
    prepare_base_model.main()
  File "/home/fintechsys/MLflow projects/kidney-Disease-classification-Deep-Learning--project/src/cnnClassifier/pipeline/stage_03_model_training.py", line 21, in main
    training.train()
  File "/home/fintechsys/MLflow projects/kidney-Disease-classification-Deep-Learning--project/src/cnnClassifier/components/model_training.py", line 76, in train
    self.model.fit(
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):
    File "main.py", line 41, in <module>
      prepare_base_model.main()
    File "/home/fintechsys/MLflow projects/kidney-Disease-classification-Deep-Learning--project/src/cnnClassifier/pipeline/stage_03_model_training.py", line 21, in main
      training.train()
    File "/home/fintechsys/MLflow projects/kidney-Disease-classification-Deep-Learning--project/src/cnnClassifier/components/model_training.py", line 76, in train
      self.model.fit(
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/training.py", line 1051, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/training.py", line 1109, in compute_loss
      return self.compiled_loss(
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/engine/compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/losses.py", line 142, in __call__
      losses = call_fn(y_true, y_pred)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/losses.py", line 268, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/losses.py", line 1984, in categorical_crossentropy
      return backend.categorical_crossentropy(
    File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/backend.py", line 5565, in categorical_crossentropy
      return tf.nn.softmax_cross_entropy_with_logits(
Node: 'categorical_crossentropy/softmax_cross_entropy_with_logits'
logits and labels must be broadcastable: logits_size=[16,3] labels_size=[16,2]
	 [[{{node categorical_crossentropy/softmax_cross_entropy_with_logits}}]] [Op:__inference_train_function_1463]
[2024-02-06 20:28:00,326: INFO: main: Welcom to our custom log]
[2024-02-06 20:28:00,326: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-06 20:28:00,327: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 20:28:00,328: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 20:28:00,328: INFO: common: created directory at: artifacts]
[2024-02-06 20:28:00,328: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-06 20:28:00,329: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-06 20:28:52,208: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-06 20:28:52,577: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-06 20:28:52,577: INFO: main: *******************]
[2024-02-06 20:28:52,577: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-06 20:28:52,578: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 20:28:52,579: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 20:28:52,579: INFO: common: created directory at: artifacts]
[2024-02-06 20:28:52,579: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-06 20:28:52,892: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-06 20:28:53,089: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-06 20:28:53,089: INFO: main: *******************]
[2024-02-06 20:28:53,089: INFO: main: >>>>>> stage training started <<<<<<]
[2024-02-06 20:28:53,090: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 20:28:53,091: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 20:28:53,091: INFO: common: created directory at: artifacts]
[2024-02-06 20:28:53,091: INFO: common: created directory at: artifacts/training]
[2024-02-06 20:29:48,808: INFO: main: >>>>>> stage training completed <<<<<<

x==========x]
[2024-02-06 20:29:48,808: INFO: main: *******************]
[2024-02-06 20:29:48,808: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-02-06 20:29:48,810: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 20:29:48,811: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 20:29:48,811: INFO: common: created directory at: artifacts]
[2024-02-06 20:30:06,418: INFO: common: json file saved at: scores.json]
[2024-02-06 20:30:06,420: INFO: common: json file saved at: scores.json]
[2024-02-06 20:30:09,678: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-06 20:30:10,001: INFO: builder_impl: Assets written to: /tmp/tmphumvqrtg/model/data/model/assets]
[2024-02-06 20:31:52,087: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-02-06 20:32:37,631: INFO: main: Welcom to our custom log]
[2024-02-06 20:32:37,631: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-06 20:32:37,633: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 20:32:37,633: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 20:32:37,634: INFO: common: created directory at: artifacts]
[2024-02-06 20:32:37,634: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-06 20:32:37,634: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-06 20:33:29,140: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-06 20:33:29,431: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-06 20:33:29,431: INFO: main: *******************]
[2024-02-06 20:33:29,431: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-06 20:33:29,432: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 20:33:29,433: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 20:33:29,433: INFO: common: created directory at: artifacts]
[2024-02-06 20:33:29,434: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-06 20:33:29,694: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-06 20:33:29,893: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-06 20:33:29,894: INFO: main: *******************]
[2024-02-06 20:33:29,894: INFO: main: >>>>>> stage training started <<<<<<]
[2024-02-06 20:33:29,895: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 20:33:29,896: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 20:33:29,896: INFO: common: created directory at: artifacts]
[2024-02-06 20:33:29,896: INFO: common: created directory at: artifacts/training]
[2024-02-06 20:35:06,182: INFO: main: >>>>>> stage training completed <<<<<<

x==========x]
[2024-02-06 20:35:06,183: INFO: main: *******************]
[2024-02-06 20:35:06,183: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-02-06 20:35:06,184: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 20:35:06,185: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 20:35:06,185: INFO: common: created directory at: artifacts]
[2024-02-06 20:35:16,986: INFO: common: json file saved at: scores.json]
[2024-02-06 20:35:16,988: INFO: common: json file saved at: scores.json]
[2024-02-06 20:35:20,334: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-06 20:35:20,687: INFO: builder_impl: Assets written to: /tmp/tmpfvertkz6/model/data/model/assets]
[2024-02-06 20:37:02,977: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-02-06 20:40:43,829: INFO: main: Welcom to our custom log]
[2024-02-06 20:40:43,829: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-06 20:40:43,831: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 20:40:43,832: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 20:40:43,832: INFO: common: created directory at: artifacts]
[2024-02-06 20:40:43,832: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-06 20:40:43,832: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-06 20:41:35,565: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-06 20:41:35,862: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-06 20:41:35,862: INFO: main: *******************]
[2024-02-06 20:41:35,862: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-06 20:41:35,863: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 20:41:35,864: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 20:41:35,864: INFO: common: created directory at: artifacts]
[2024-02-06 20:41:35,864: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-06 20:41:36,122: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-06 20:41:36,302: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-06 20:41:36,302: INFO: main: *******************]
[2024-02-06 20:41:36,302: INFO: main: >>>>>> stage training started <<<<<<]
[2024-02-06 20:41:36,303: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 20:41:36,304: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 20:41:36,304: INFO: common: created directory at: artifacts]
[2024-02-06 20:41:36,305: INFO: common: created directory at: artifacts/training]
[2024-02-06 20:42:07,666: INFO: main: >>>>>> stage training completed <<<<<<

x==========x]
[2024-02-06 20:42:07,666: INFO: main: *******************]
[2024-02-06 20:42:07,666: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-02-06 20:42:07,667: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 20:42:07,668: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 20:42:07,668: INFO: common: created directory at: artifacts]
[2024-02-06 20:42:18,023: INFO: common: json file saved at: scores.json]
[2024-02-06 20:42:18,023: INFO: common: json file saved at: scores.json]
[2024-02-06 20:42:21,078: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-06 20:42:21,428: INFO: builder_impl: Assets written to: /tmp/tmpfx769xwb/model/data/model/assets]
[2024-02-06 20:44:01,414: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-02-06 21:34:10,080: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-06 21:34:10,081: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 21:34:10,082: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 21:34:10,083: INFO: common: created directory at: artifacts]
[2024-02-06 21:34:10,083: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-06 21:34:10,083: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-06 21:35:10,113: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-06 21:35:10,387: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-06 21:35:12,571: INFO: stage_02_prepare_base_model: *******************]
[2024-02-06 21:35:12,571: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-06 21:35:12,573: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 21:35:12,574: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 21:35:12,574: INFO: common: created directory at: artifacts]
[2024-02-06 21:35:12,575: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-06 21:35:12,840: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-06 21:35:12,981: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-06 21:35:15,090: INFO: stage_03_model_training: *******************]
[2024-02-06 21:35:15,090: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-02-06 21:35:15,092: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 21:35:15,094: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 21:35:15,094: INFO: common: created directory at: artifacts]
[2024-02-06 21:35:15,094: INFO: common: created directory at: artifacts/training]
[2024-02-06 21:37:04,562: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-02-06 21:37:07,171: INFO: stage_04_model_evaluation: *******************]
[2024-02-06 21:37:07,171: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-02-06 21:37:07,173: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-06 21:37:07,174: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-06 21:37:07,174: INFO: common: created directory at: artifacts]
[2024-02-06 21:37:18,242: INFO: common: json file saved at: scores.json]
[2024-02-06 21:37:18,242: INFO: common: json file saved at: scores.json]
[2024-02-06 21:37:21,778: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-06 21:37:22,180: INFO: builder_impl: Assets written to: /tmp/tmpyhz_iwfp/model/data/model/assets]
[2024-02-06 21:39:05,156: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-02-07 09:42:04,758: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.88.123:8080]
[2024-02-07 09:42:04,758: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-02-07 09:42:11,429: INFO: _internal: 127.0.0.1 - - [07/Feb/2024 09:42:11] "GET / HTTP/1.1" 200 -]
[2024-02-07 09:42:53,112: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/flask_cors/decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "/home/fintechsys/MLflow projects/kidney-Disease-classification-Deep-Learning--project/src/cnnClassifier/pipeline/prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/saving/saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/saving/legacy/save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model/model.h5
[2024-02-07 09:42:53,117: INFO: _internal: 127.0.0.1 - - [07/Feb/2024 09:42:53] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-02-07 09:44:29,734: INFO: _internal: 127.0.0.1 - - [07/Feb/2024 09:44:29] "GET / HTTP/1.1" 200 -]
[2024-02-07 09:44:43,056: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/flask_cors/decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "/home/fintechsys/MLflow projects/kidney-Disease-classification-Deep-Learning--project/src/cnnClassifier/pipeline/prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/saving/saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/saving/legacy/save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model/model.h5
[2024-02-07 09:44:43,056: INFO: _internal: 127.0.0.1 - - [07/Feb/2024 09:44:43] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-02-07 09:49:48,543: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.88.123:5000]
[2024-02-07 09:49:48,543: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-02-07 09:49:52,117: INFO: _internal: 127.0.0.1 - - [07/Feb/2024 09:49:52] "GET / HTTP/1.1" 200 -]
[2024-02-07 09:50:02,266: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/flask_cors/decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "/home/fintechsys/MLflow projects/kidney-Disease-classification-Deep-Learning--project/src/cnnClassifier/pipeline/prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/saving/saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/saving/legacy/save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model/model.h5
[2024-02-07 09:50:02,267: INFO: _internal: 127.0.0.1 - - [07/Feb/2024 09:50:02] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-02-07 09:53:50,695: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.88.123:5000]
[2024-02-07 09:53:50,695: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-02-07 09:53:55,270: INFO: _internal: 127.0.0.1 - - [07/Feb/2024 09:53:55] "GET / HTTP/1.1" 200 -]
[2024-02-07 09:54:01,234: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/flask_cors/decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "/home/fintechsys/MLflow projects/kidney-Disease-classification-Deep-Learning--project/src/cnnClassifier/pipeline/prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/saving/saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/fintechsys/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/saving/legacy/save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model/model.h5
[2024-02-07 09:54:01,236: INFO: _internal: 127.0.0.1 - - [07/Feb/2024 09:54:01] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-02-07 09:57:33,041: INFO: stage_03_model_training: *******************]
[2024-02-07 09:57:33,041: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-02-07 09:57:33,045: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-07 09:57:33,046: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 09:57:33,046: INFO: common: created directory at: artifacts]
[2024-02-07 09:57:33,047: INFO: common: created directory at: artifacts/training]
[2024-02-07 09:58:29,243: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-02-07 09:58:32,208: INFO: stage_04_model_evaluation: *******************]
[2024-02-07 09:58:32,209: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-02-07 09:58:32,210: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-07 09:58:32,211: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-07 09:58:32,211: INFO: common: created directory at: artifacts]
[2024-02-07 09:58:49,968: INFO: common: json file saved at: scores.json]
[2024-02-07 09:58:49,968: INFO: common: json file saved at: scores.json]
[2024-02-07 09:58:52,772: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-07 09:58:53,138: INFO: builder_impl: Assets written to: /tmp/tmpq3_pgj4c/model/data/model/assets]
[2024-02-07 10:05:07,734: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-02-07 12:10:09,350: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.88.123:5001]
[2024-02-07 12:10:09,350: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-02-07 12:10:12,805: INFO: _internal: 127.0.0.1 - - [07/Feb/2024 12:10:12] "GET / HTTP/1.1" 200 -]
[2024-02-07 12:10:22,315: INFO: _internal: 127.0.0.1 - - [07/Feb/2024 12:10:22] "POST /predict HTTP/1.1" 200 -]
[2024-02-07 12:10:37,317: INFO: _internal: 127.0.0.1 - - [07/Feb/2024 12:10:37] "POST /predict HTTP/1.1" 200 -]
[2024-02-07 12:10:39,859: INFO: _internal: 127.0.0.1 - - [07/Feb/2024 12:10:39] "POST /predict HTTP/1.1" 200 -]
[2024-02-07 12:33:08,785: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.88.123:5001]
[2024-02-07 12:33:08,786: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-02-07 12:33:11,956: INFO: _internal: 127.0.0.1 - - [07/Feb/2024 12:33:11] "GET / HTTP/1.1" 200 -]
[2024-02-07 12:33:24,336: INFO: _internal: 127.0.0.1 - - [07/Feb/2024 12:33:24] "POST /predict HTTP/1.1" 200 -]
[2024-02-07 12:34:10,479: INFO: _internal: 127.0.0.1 - - [07/Feb/2024 12:34:10] "GET /train HTTP/1.1" 200 -]
[2024-02-07 12:34:10,518: INFO: _internal: 127.0.0.1 - - [07/Feb/2024 12:34:10] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
